scheduler_iam_policies:
  ecs-runtask:
    action:
      - ecs:RunTask
    condition:
      ArnLike:
        ecs:cluster: 
          Fn::Join: 
            - /
            - - Fn::Sub: arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster
              - Ref: EcsCluster
  ecs-pass-role:
    action:
      - iam:PassRole
    condition:
      StringLike:
        iam:PassedToService: "ecs-tasks.amazonaws.com"
