scheduler_iam_policies:
  ecs-runtask:
    action:
      - ecs:RunTask
    condition:
      ArnLike:
        ecs:cluster: 
          - Ref: EcsClusterArn
  ecs-pass-role:
    action:
      - iam:PassRole
    condition:
      StringLike:
        iam:PassedToService: "ecs-tasks.amazonaws.com"
